#163454395 api endpoint that edits name of a specific party
femitj/Politico pull request #17
Opened 2019-01-24 18:42 UTC by femitj

**What does this PR do?**

creates API endpoint that edits or updates name of a specific political party

**Description of the task to be completed**

Ensure the following endpoints are working as they should

PATCH/api/v1/parties/<party-id>/name

**How should this be tested manually**

 - After you clone the repo,
 - cd into it and run npm install to install node modules.
 - Make sure you have nodejs and express installed.
 - Afterwards, run npm start to initiate the app.
 - test endpoint above using postman with localhost:8080 as the host

What are the relevant pivotal stories
#163454395

2019-01-24 19:30 UTC, andela-gike requested changes

2019-01-24 19:30 UTC, andela-gike commented on src/controllers/PartyControllers.js
>        }],
Your response message is not descriptive enough

2019-01-24 19:30 UTC, andela-gike commented on src/controllers/PartyControllers.js
> +        name: party.name,
Same here as the comment above

2019-01-25 11:48 UTC, andela-gike approved these changes

2019-01-25 12:08 UTC, femitj commented on src/controllers/PartyControllers.js
>        }],
![screenshot 31](https://user-images.githubusercontent.com/40898511/51703760-80473e00-2017-11e9-9739-fd4d92b03bd1.png)

I made changes because i was trying to adhere to the response spec given.
dont I have to strictly adhere to that??

2019-01-25 12:09 UTC, merged